#!/usr/bin/env python3
import re
import sys
from pathlib import Path


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*", "", text)
    return text


def extract_blocks(text: str, keyword: str):
    pattern = re.compile(rf"\b{keyword}\s+([A-Za-z_]\w*)\s*\{{", re.M)
    pos = 0
    while True:
        match = pattern.search(text, pos)
        if not match:
            return
        name = match.group(1)
        brace_start = match.end() - 1
        depth = 0
        i = brace_start
        while i < len(text):
            ch = text[i]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    body = text[brace_start + 1:i]
                    yield name, body
                    pos = i + 1
                    break
            i += 1
        else:
            raise SystemExit(f"Unclosed block for {keyword} {name}")


FIELD_RE = re.compile(
    r"^\s*(?:optional|required|repeated)?\s*"
    r"(?P<type>[A-Za-z_]\w*)\s+"
    r"(?P<name>[A-Za-z_]\w*)\s*=\s*"
    r"(?P<id>\d+)\s*"
    r"(?:\[[^\]]*\])?\s*;\s*$",
    re.M,
)


TYPE_INFO = {
    "uint32": {"kind": "varint", "default": "0"},
    "uint64": {"kind": "varint", "default": "0"},
    "int32": {"kind": "varint", "default": "0"},
    "int64": {"kind": "varint", "default": "0"},
    "bool": {"kind": "bool", "default": "false"},
    "string": {"kind": "len", "default": '""'},
    "bytes": {"kind": "len", "default": '""'},
}


def parse_proto(text: str):
    text = strip_comments(text)
    package_match = re.search(r"\bpackage\s+([A-Za-z_][\w.]*)\s*;", text)
    package_name = package_match.group(1) if package_match else ""

    messages = []
    for msg_name, body in extract_blocks(text, "message"):
        fields = []
        for field in FIELD_RE.finditer(body):
            ftype = field.group("type")
            if ftype not in TYPE_INFO:
                raise SystemExit(f"Unsupported field type: {ftype} in message {msg_name}")
            fields.append({
                "type": ftype,
                "name": field.group("name"),
                "id": int(field.group("id")),
            })
        messages.append({
            "name": msg_name,
            "fields": sorted(fields, key=lambda item: item["id"]),
        })

    if not messages:
        raise SystemExit("No message definitions found")

    return package_name, messages


HEADER = """-- Generated by tools/proto_to_lua.py
-- Do not edit by hand.

local M = {}

local function encode_varint(value)
    value = math.floor(tonumber(value) or 0)
    if value < 0 then
        error("proto varint encoder only supports non-negative values")
    end

    local out = {}
    repeat
        local byte = value % 128
        value = math.floor(value / 128)
        if value > 0 then
            byte = byte + 128
        end
        out[#out + 1] = string.char(byte)
    until value == 0

    return table.concat(out)
end

local function decode_varint(buf, idx)
    local value = 0
    local shift = 0

    while true do
        local byte = string.byte(buf, idx)
        if not byte then
            error("proto varint truncated")
        end

        value = value + (byte % 128) * (2 ^ shift)
        idx = idx + 1

        if byte < 128 then
            return value, idx
        end

        shift = shift + 7
        if shift > 63 then
            error("proto varint overflow")
        end
    end
end

local function encode_key(field_no, wire_type)
    return encode_varint(field_no * 8 + wire_type)
end

local function encode_varint_field(field_no, value)
    return encode_key(field_no, 0) .. encode_varint(value)
end

local function encode_len_field(field_no, value)
    value = value or ""
    return encode_key(field_no, 2) .. encode_varint(#value) .. value
end

local function decode_len(buf, idx)
    local size
    size, idx = decode_varint(buf, idx)
    local last = idx + size - 1
    if last > #buf then
        error("proto length-delimited field truncated")
    end
    return string.sub(buf, idx, last), last + 1
end

local function parse_fields(buf)
    local idx = 1
    local fields = {}

    while idx <= #buf do
        local key
        key, idx = decode_varint(buf, idx)
        local field_no = math.floor(key / 8)
        local wire_type = key % 8

        if wire_type == 0 then
            local value
            value, idx = decode_varint(buf, idx)
            fields[field_no] = value
        elseif wire_type == 2 then
            local value
            value, idx = decode_len(buf, idx)
            fields[field_no] = value
        else
            error("unsupported wire type: " .. tostring(wire_type))
        end
    end

    return fields
end

"""


def build_module(package_name, messages):
    out = [HEADER]
    if package_name:
        out.append(f'M.__package = "{package_name}"\n\n')

    for msg in messages:
        name = msg["name"]
        out.append(f"function M.encode_{name}(msg)\n")
        out.append("    msg = msg or {}\n")
        out.append("    local out = {}\n")
        for field in msg["fields"]:
            info = TYPE_INFO[field["type"]]
            fname = field["name"]
            fid = field["id"]
            if info["kind"] == "varint":
                if field["type"] == "bool":
                    out.append(f"    if msg.{fname} ~= nil then out[#out + 1] = encode_varint_field({fid}, msg.{fname} and 1 or 0) end\n")
                else:
                    out.append(f"    if msg.{fname} ~= nil then out[#out + 1] = encode_varint_field({fid}, msg.{fname}) end\n")
            else:
                out.append(f"    if msg.{fname} ~= nil then out[#out + 1] = encode_len_field({fid}, msg.{fname}) end\n")
        out.append("    return table.concat(out)\n")
        out.append("end\n\n")

        out.append(f"function M.decode_{name}(buf)\n")
        out.append("    local fields = parse_fields(buf or \"\")\n")
        out.append("    return {\n")
        for field in msg["fields"]:
            info = TYPE_INFO[field["type"]]
            fname = field["name"]
            fid = field["id"]
            if field["type"] == "bool":
                out.append(f"        {fname} = (fields[{fid}] or 0) ~= 0,\n")
            else:
                out.append(f"        {fname} = fields[{fid}] or {info['default']},\n")
        out.append("    }\n")
        out.append("end\n\n")

    out.append("return M\n")
    return "".join(out)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("Usage: proto_to_lua.py <input.proto> <output.lua>")

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])

    package_name, messages = parse_proto(src.read_text(encoding="utf-8"))
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(build_module(package_name, messages), encoding="utf-8")
    print(f"generated {dst}")


if __name__ == "__main__":
    main()
